package proyecto.cards;

import proyecto.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dylan
 */
public class CardMain extends javax.swing.JFrame {

    /**
     * Creates new form cardMain
     */
    public CardMain() {
        initComponents();
        this.setTitle("Menu tarjetas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nav_debit = new javax.swing.JButton();
        nav_credit = new javax.swing.JButton();
        nav_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_debit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/assets/icons/tarjeta-de-debito.png"))); // NOI18N
        nav_debit.setText("Tarjeta de Debito");
        nav_debit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nav_debit.setIconTextGap(20);
        nav_debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_debitActionPerformed(evt);
            }
        });
        jPanel1.add(nav_debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 300, 100));

        nav_credit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/assets/icons/tarjeta-de-credito(1).png"))); // NOI18N
        nav_credit.setText("Tarjeta de Credito");
        nav_credit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nav_credit.setIconTextGap(20);
        nav_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_creditActionPerformed(evt);
            }
        });
        jPanel1.add(nav_credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 300, 100));

        nav_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/assets/icons/atras.png"))); // NOI18N
        nav_back.setToolTipText("Regresar");
        nav_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_backActionPerformed(evt);
            }
        });
        jPanel1.add(nav_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nav_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_creditActionPerformed

    private void nav_debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_debitActionPerformed
        // TODO add your handling code here:
        DebitCard debitCard = new DebitCard();
        debitCard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nav_debitActionPerformed

    private void nav_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_backActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nav_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nav_back;
    private javax.swing.JButton nav_credit;
    private javax.swing.JButton nav_debit;
    // End of variables declaration//GEN-END:variables
}
