/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.views;

import com.proyecto.main.Dashboard;
import com.proyecto.utils.Utils;
import com.proyecto.views.cards.Credit;
import com.proyecto.views.cards.Debit;

/**
 *
 * @author dylan
 */
public class Cards extends javax.swing.JPanel {
    
    private Utils util;
    /**
     * Creates new form Cards
     */
    public Cards() {
        initComponents();
    }
    
    private void handleHiddenButtons(){
        btn_credit.setVisible(false);
        btn_debit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        btn_debit = new javax.swing.JButton();
        btn_credit = new javax.swing.JButton();

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_debit.setBackground(new java.awt.Color(18, 90, 173));
        btn_debit.setForeground(new java.awt.Color(255, 255, 255));
        btn_debit.setText("Debito");
        btn_debit.setBorder(null);
        btn_debit.setBorderPainted(false);
        btn_debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_debitActionPerformed(evt);
            }
        });

        btn_credit.setBackground(new java.awt.Color(18, 90, 173));
        btn_credit.setForeground(new java.awt.Color(255, 255, 255));
        btn_credit.setText("Credito");
        btn_credit.setBorder(null);
        btn_credit.setBorderPainted(false);
        btn_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_debit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_credit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(btn_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btn_debit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        container.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 738, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creditActionPerformed
        // TODO add your handling code here:
        util = new Utils();
        Credit credit = new Credit();
        Dashboard.txt_title.setText("Tarjeta de credito");
        util.ShowPanel(credit, content, 738, 528);
        handleHiddenButtons();
    }//GEN-LAST:event_btn_creditActionPerformed

    private void btn_debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_debitActionPerformed
        // TODO add your handling code here:
        util = new Utils();
        Debit debit = new Debit();
        Dashboard.txt_title.setText("Tarjeta de debito");
        util.ShowPanel(debit, content, 738, 528);
        handleHiddenButtons();
    }//GEN-LAST:event_btn_debitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_credit;
    private javax.swing.JButton btn_debit;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
}
