/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.views;

import com.proyecto.components.SchoolComponent;
import com.proyecto.models.Student;
import com.proyecto.utils.Utils;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
public class School extends javax.swing.JPanel {
    
    private final Utils util = new Utils();
    
    /**
     * Creates new form School
     */
    public School() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_photo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_files = new javax.swing.JButton();
        btn_tramitar = new javax.swing.JButton();
        txt_birthday = new com.toedter.calendar.JDateChooser();
        txt_shift = new javax.swing.JComboBox<>();
        txt_quarter = new javax.swing.JComboBox<>();
        txt_career = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Datos del alumno");

        jLabel2.setText("Nombre(s)");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Cuatrimestre");

        jLabel5.setText("Turno");

        jLabel6.setText("Carrera");

        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("Foto");

        btn_files.setBackground(new java.awt.Color(18, 90, 173));
        btn_files.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-alt-regular-24.png"))); // NOI18N
        btn_files.setBorder(null);
        btn_files.setBorderPainted(false);
        btn_files.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filesActionPerformed(evt);
            }
        });

        btn_tramitar.setBackground(new java.awt.Color(18, 90, 173));
        btn_tramitar.setForeground(new java.awt.Color(255, 255, 255));
        btn_tramitar.setText("Tramitar");
        btn_tramitar.setBorder(null);
        btn_tramitar.setBorderPainted(false);
        btn_tramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tramitarActionPerformed(evt);
            }
        });

        txt_shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino" }));

        txt_quarter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° Primer", "2° Segundo", "3° Tercer", "4° Cuarto", "5° Quinto", "6° Sexto", "7° Septimo", "8° Octavo", "9° Noveno", "10° Decimo", "11° Onceavo" }));

        txt_career.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administración de Empresas ", "Administración de Empresas Turísticas ", "Relaciones Internacionales ", "Contaduría Pública y Finanzas ", "Derecho ", "Mercadotecnia y Publicidad ", "Gastronomía", "Periodismo y Ciencias de la Comunicación", "Diseño de Modas", "Pedagogía ", "Cultura Física y Educación del Deporte ", "Idiomas ( Inglés y Francés ) ", "Psicología", "Diseño de Interiores ", "Diseño Gráfico ", "Ingeniería en Logística y Transporte ", "Ingeniero Arquitecto ", "Informática Administrativa y Fiscal ", "Ingeniería en Sistemas Computacionales ", "Ingeniería Mecánica Automotriz " }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txt_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btn_files, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txt_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btn_tramitar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txt_career, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txt_quarter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_career, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quarter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_shift, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txt_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_files, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_tramitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filesActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        int seleccion = f.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){

            File file = f.getSelectedFile();
            
            String extensionFile = util.getExtension(file);
            
            if(!util.verifyFile(extensionFile)){
                 JOptionPane.showMessageDialog(null, "Solo se aceptan archivos con extension png, jpeg, jpg.", "Archivo incorrecto", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            
            txt_photo.setText(file.getPath());         
        }
    }//GEN-LAST:event_btn_filesActionPerformed

    private void btn_tramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tramitarActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        String nombre = txt_name.getText();
        String apellido = txt_lastname.getText();
        String fecha = ff.format(txt_birthday.getDate().getTime());
        String foto = txt_photo.getText();
        String carrera = txt_career.getSelectedItem().toString();
        String cuatrimestre = txt_quarter.getSelectedItem().toString();
        String turno = txt_shift.getSelectedItem().toString();
        
        Student student = new Student(nombre, apellido, fecha, foto, carrera, cuatrimestre, turno);
        
        util.ShowPanel(new SchoolComponent(student), content, 738, 528);
    }//GEN-LAST:event_btn_tramitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_files;
    private javax.swing.JButton btn_tramitar;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser txt_birthday;
    private javax.swing.JComboBox<String> txt_career;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_photo;
    private javax.swing.JComboBox<String> txt_quarter;
    private javax.swing.JComboBox<String> txt_shift;
    // End of variables declaration//GEN-END:variables
}
