/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto_compiladores.views.cards;

import com.mycompany.proyecto_compiladores.Main;
import com.mycompany.proyecto_compiladores.models.Customer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


public class CreditCard extends javax.swing.JFrame {
    private Customer customer;
    /**
     * Creates new form CreditCard
     */
    public CreditCard() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tarjeta de credito");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_date = new com.toedter.calendar.JDateChooser();
        txt_address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_salary = new javax.swing.JComboBox<>();
        txt_booth = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_tramitar = new javax.swing.JButton();
        nav_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre completo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 42));

        txt_date.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 48));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 42));

        jLabel5.setText("Domicilio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel4.setText("Fecha de nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Correo Electronico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, 42));

        txt_salary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "$1 -  $4,000", "$4,001 - $8,000", "$8,001 - $16,000", "Más de $16,000" }));
        jPanel1.add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 290, 42));
        jPanel1.add(txt_booth, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 290, 42));

        jLabel1.setText("Puesto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel2.setText("Salario Mensual");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        btn_tramitar.setText("Tramitar");
        btn_tramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tramitarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tramitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        nav_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atras.png"))); // NOI18N
        nav_back.setToolTipText("Regresar");
        nav_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_backActionPerformed(evt);
            }
        });
        jPanel1.add(nav_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nav_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_backActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        setTitle("Tarjeta de credito");
        dispose();
    }//GEN-LAST:event_nav_backActionPerformed

    private void btn_tramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tramitarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = txt_name.getText();
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            String date = ff.format(txt_date.getDate().getTime());
            Date d = ff.parse(date);
            String direccion = txt_address.getText();
            String correo = txt_email.getText();
            String puesto = txt_booth.getText();
            String salario = txt_salary.getSelectedItem().toString();
            
            customer = new Customer(nombre, d, correo, direccion, puesto, salario);
            
            new CreditCardCustomer(customer).setVisible(true);
            dispose();
            
        } catch (ParseException ex) {
           
        }
    }//GEN-LAST:event_btn_tramitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tramitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nav_back;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_booth;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JComboBox<String> txt_salary;
    // End of variables declaration//GEN-END:variables
}
