/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.components;

import com.proyecto.models.Customer;
import com.proyecto.utils.Utils;
import com.proyecto.views.Cards;
import java.awt.Color;

/**
 *
 * @author dylan
 */
public class CreditComponent extends javax.swing.JPanel {
    
    private final String SALUDO = "Hola %s";
    private final String CARD = "4000 1234 %s %s"; 
    private final Utils util = new Utils();
    
    /**
     * Creates new form CreditComponent
     * @param customer
     */
    public CreditComponent(Customer customer) {
        initComponents();
        initStyles();
        initValues(customer);
    }

    private void initStyles(){
        txt_saludo.putClientProperty("FlatLaf.style", "font: bold $h2.font");
        txt_saludo.setForeground(Color.BLACK);
        txt_card.putClientProperty("FlatLaf.style", "font: $h1.font");
        txt_card.setForeground(Color.BLACK);
    }
    
    private void initValues(Customer customer){
        String name = util.capitalizeFirstLetter(customer.getFullName().toLowerCase());
        txt_saludo.setText(String.format(SALUDO, name));
        txt_card.setText(String.format(CARD, util.generateRandomNumbers(4), util.generateRandomNumbers(4)));
        int credit = Integer.parseInt(util.getCredit(customer.getMonthlySalary()));
        txt_credito.setText(String.valueOf(util.formatoMoneda(credit)));
        txt_corte.setText(util.getNextMonth("06"));
        txt_pago.setText(util.getNextMonth("16"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_credito = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_corte = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_pago = new javax.swing.JLabel();
        txt_saludo = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_card = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Credito disponible:");

        txt_credito.setText("$ 10,000.00");

        jLabel6.setText("Fecha de corte:");

        txt_corte.setText("16 / {}");

        jLabel8.setText("Fecha de pago:");

        txt_pago.setText("6 / {}");

        txt_saludo.setText("Hola {}.");

        btn_back.setBackground(new java.awt.Color(18, 90, 173));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Regresar");
        btn_back.setBorder(null);
        btn_back.setBorderPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel2.setText("Esta es tu nueva tarjeta de credito.");

        txt_card.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_card.setText("4000  1234 {} {}");

        jLabel1.setText("Intereses:");

        jLabel3.setText("5.0 %");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_saludo)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txt_card, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_credito)
                    .addComponent(txt_corte)
                    .addComponent(txt_pago)
                    .addComponent(jLabel3))
                .addGap(76, 76, 76))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt_saludo)
                .addGap(26, 26, 26)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(txt_card, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_credito))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_corte))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pago))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(content, new Cards(), 738, 528);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt_card;
    private javax.swing.JLabel txt_corte;
    private javax.swing.JLabel txt_credito;
    private javax.swing.JLabel txt_pago;
    private javax.swing.JLabel txt_saludo;
    // End of variables declaration//GEN-END:variables
}
