/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.components;

import com.proyecto.models.Customer;
import com.proyecto.utils.Utils;
import com.proyecto.views.Membership;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author dylan
 */
public class MembershipComponent extends javax.swing.JPanel {

    private final Utils util = new Utils();
    /**
     * Creates new form MembershipComponent
     * @param customer
     */
    public MembershipComponent(Customer customer) {
        initComponents();
        initStyles();
        initCustomer(customer);
    }

    private void initStyles() {
        txt_saludo.putClientProperty("FlatLaf.style", "font: bold $h2.font");
        txt_saludo.setForeground(Color.black);
        txt_vip.putClientProperty("FlatLaf.style", "font: bold $h1.font");
        txt_vip.setForeground(Color.white);
        txt_membership.putClientProperty("FlatLaf.style", "font: $h3.font");
        txt_membership.setForeground(Color.white);
        txt_titleHolder.putClientProperty("FlatLaf.style", "font: bold $h2.font");
        txt_titleHolder.setForeground(Color.white);
        txt_holder.putClientProperty("FlatLaf.style", "font: $h3.font");
        txt_holder.setForeground(Color.white);
        txt_club.putClientProperty("FlatLaf.style", "font: bold $h1.font");
        txt_club.setForeground(Color.white);
       
    }

    private void initCustomer(Customer customer) {
        membership.setBackground(util.bgCard(customer.getTypeOfMembership()));
        txt_membership.setText(customer.getTypeOfMembership().toUpperCase());
        txt_saludo.setText("BIENVENIDO " + customer.getName().toUpperCase() + " " + customer.getLastname().toUpperCase());
        txt_vigencia.setText(customer.getValidity().toUpperCase());
        txt_holder.setText(customer.getName().toUpperCase() + " " + customer.getLastname().toUpperCase());
        String textQr = "Nombre: " + customer.getName() + " " + customer.getLastname() + "\n"
                + "Correo Electronico: " + customer.getEmail() + "\n"
                + "Fecha de nacimiento: " + customer.getBirthday();

        ImageIcon icon = new ImageIcon(util.GenerateQR(textQr, 125));
        txt_qr.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        txt_saludo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        membership = new javax.swing.JPanel();
        txt_vip = new javax.swing.JLabel();
        txt_titleHolder = new javax.swing.JLabel();
        txt_club = new javax.swing.JLabel();
        txt_qr = new javax.swing.JLabel();
        txt_holder = new javax.swing.JLabel();
        txt_membership = new javax.swing.JLabel();
        txt_vigencia = new javax.swing.JLabel();
        txt_vig = new javax.swing.JLabel();
        btn_privileges = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        content.setBackground(new java.awt.Color(255, 255, 255));

        txt_saludo.setText("Bienvenido {}.");

        jLabel2.setText("Esta es tu nueva membresía para Club Deportivo.");

        txt_vip.setForeground(new java.awt.Color(255, 255, 255));
        txt_vip.setText("VIP");

        txt_titleHolder.setForeground(new java.awt.Color(255, 255, 255));
        txt_titleHolder.setText("TITULAR CLIENTE");

        txt_club.setForeground(new java.awt.Color(255, 255, 255));
        txt_club.setText("CLUB DEPORTIVO");

        txt_holder.setForeground(new java.awt.Color(255, 255, 255));
        txt_holder.setText("{}");

        txt_membership.setForeground(new java.awt.Color(255, 255, 255));
        txt_membership.setText("{}");

        txt_vigencia.setForeground(new java.awt.Color(255, 255, 255));
        txt_vigencia.setText("{}");

        txt_vig.setForeground(new java.awt.Color(255, 255, 255));
        txt_vig.setText("VIGENCIA");

        javax.swing.GroupLayout membershipLayout = new javax.swing.GroupLayout(membership);
        membership.setLayout(membershipLayout);
        membershipLayout.setHorizontalGroup(
            membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membershipLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(membershipLayout.createSequentialGroup()
                        .addComponent(txt_membership, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(membershipLayout.createSequentialGroup()
                        .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_vip)
                            .addComponent(txt_titleHolder)
                            .addComponent(txt_holder, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, membershipLayout.createSequentialGroup()
                                .addComponent(txt_club)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, membershipLayout.createSequentialGroup()
                                .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(membershipLayout.createSequentialGroup()
                                        .addComponent(txt_vig)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101))))))
        );
        membershipLayout.setVerticalGroup(
            membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membershipLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vip)
                    .addComponent(txt_club))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_membership)
                .addGap(7, 7, 7)
                .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vigencia)
                    .addComponent(txt_vig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(membershipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, membershipLayout.createSequentialGroup()
                        .addComponent(txt_titleHolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_holder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_qr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btn_privileges.setBackground(new java.awt.Color(18, 90, 173));
        btn_privileges.setForeground(new java.awt.Color(255, 255, 255));
        btn_privileges.setText("Ver privilegios");
        btn_privileges.setBorder(null);
        btn_privileges.setBorderPainted(false);
        btn_privileges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_privilegesActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(18, 90, 173));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Regresar");
        btn_back.setBorder(null);
        btn_back.setBorderPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_saludo)
                            .addComponent(membership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_privileges, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txt_saludo)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(membership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_privileges, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new Membership(), content, 738, 528);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_privilegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_privilegesActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new PrivilegesComponent(txt_holder.getText(), txt_membership.getText()), content, 738, 528);
    }//GEN-LAST:event_btn_privilegesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_privileges;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel membership;
    private javax.swing.JLabel txt_club;
    private javax.swing.JLabel txt_holder;
    private javax.swing.JLabel txt_membership;
    private javax.swing.JLabel txt_qr;
    private javax.swing.JLabel txt_saludo;
    private javax.swing.JLabel txt_titleHolder;
    private javax.swing.JLabel txt_vig;
    private javax.swing.JLabel txt_vigencia;
    private javax.swing.JLabel txt_vip;
    // End of variables declaration//GEN-END:variables
}
