package com.proyecto.main;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.proyecto.utils.Utils;
import com.proyecto.views.Cards;
import com.proyecto.views.Home;
import com.proyecto.views.Identification;
import com.proyecto.views.Membership;
import com.proyecto.views.Payment;
import com.proyecto.views.School;
import java.awt.Color;

/**
 *
 * @author dylan
 */
public class Dashboard extends javax.swing.JFrame {
    
    Utils util = new Utils();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        initStyles();
        initContent();
    }

    private void initStyles() {
        txt_logo.putClientProperty("FlatLaf.style", "font: bold $h0.font");
        txt_logo.setForeground(Color.white);
        txt_title.putClientProperty("FlatLaf.style", "font: bold $h2.font");
        txt_title.setForeground(Color.white);
    }

    private void initContent() {
        Home home = new Home();
       util.ShowPanel(home, content, 738, 528);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        aside = new javax.swing.JPanel();
        txt_logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_home = new javax.swing.JButton();
        btn_membership = new javax.swing.JButton();
        btn_identification = new javax.swing.JButton();
        btn_school = new javax.swing.JButton();
        btn_payment = new javax.swing.JButton();
        btn_cards = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        txt_title = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto");
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));

        aside.setBackground(new java.awt.Color(13, 71, 161));

        txt_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_logo.setText("Proyecto");

        btn_home.setBackground(new java.awt.Color(21, 101, 192));
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-regular-24.png"))); // NOI18N
        btn_home.setText("Inicio");
        btn_home.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_home.setBorderPainted(false);
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_home.setIconTextGap(10);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_membership.setBackground(new java.awt.Color(21, 101, 192));
        btn_membership.setForeground(new java.awt.Color(255, 255, 255));
        btn_membership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diamond-regular-24.png"))); // NOI18N
        btn_membership.setText("Membresia");
        btn_membership.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_membership.setBorderPainted(false);
        btn_membership.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_membership.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_membership.setIconTextGap(10);
        btn_membership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_membershipActionPerformed(evt);
            }
        });

        btn_identification.setBackground(new java.awt.Color(21, 101, 192));
        btn_identification.setForeground(new java.awt.Color(255, 255, 255));
        btn_identification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-badge-solid-24.png"))); // NOI18N
        btn_identification.setText("Identificación");
        btn_identification.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_identification.setBorderPainted(false);
        btn_identification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_identification.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_identification.setIconTextGap(10);
        btn_identification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_identificationActionPerformed(evt);
            }
        });

        btn_school.setBackground(new java.awt.Color(21, 101, 192));
        btn_school.setForeground(new java.awt.Color(255, 255, 255));
        btn_school.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graduation-solid-24.png"))); // NOI18N
        btn_school.setText("Credencial escolar");
        btn_school.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_school.setBorderPainted(false);
        btn_school.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_school.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_school.setIconTextGap(10);
        btn_school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_schoolActionPerformed(evt);
            }
        });

        btn_payment.setBackground(new java.awt.Color(21, 101, 192));
        btn_payment.setForeground(new java.awt.Color(255, 255, 255));
        btn_payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallet-regular-24.png"))); // NOI18N
        btn_payment.setText("Pago de servicio");
        btn_payment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_payment.setBorderPainted(false);
        btn_payment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_payment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_payment.setIconTextGap(10);
        btn_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paymentActionPerformed(evt);
            }
        });

        btn_cards.setBackground(new java.awt.Color(21, 101, 192));
        btn_cards.setForeground(new java.awt.Color(255, 255, 255));
        btn_cards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit-card.png"))); // NOI18N
        btn_cards.setText("Tarjetas");
        btn_cards.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_cards.setBorderPainted(false);
        btn_cards.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cards.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cards.setIconTextGap(10);
        btn_cards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cardsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asideLayout = new javax.swing.GroupLayout(aside);
        aside.setLayout(asideLayout);
        asideLayout.setHorizontalGroup(
            asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_identification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_payment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_school, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(asideLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(btn_cards, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_membership, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asideLayout.setVerticalGroup(
            asideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asideLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txt_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_membership, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_identification, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_school, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(25, 118, 210));

        txt_title.setText("Inicio");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(654, Short.MAX_VALUE)
                .addComponent(txt_title)
                .addGap(60, 60, 60))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt_title)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(aside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cardsActionPerformed
        // TODO add your handling code here:
        Cards cards = new Cards();
        util.ShowPanel(cards, content, 738, 528);
        txt_title.setText("Tarjetas");
        
    }//GEN-LAST:event_btn_cardsActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        util.ShowPanel(home, content, 738, 528);
        txt_title.setText("Inicio");
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_membershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_membershipActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new Membership(), content, 738, 528);
        txt_title.setText("Membresias");
    }//GEN-LAST:event_btn_membershipActionPerformed

    private void btn_identificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_identificationActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new Identification(), content, 738, 528);
        txt_title.setText("INE");
    }//GEN-LAST:event_btn_identificationActionPerformed

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new Payment(), content, 738, 528);
        txt_title.setText("Pago de servicio");
    }//GEN-LAST:event_btn_paymentActionPerformed

    private void btn_schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_schoolActionPerformed
        // TODO add your handling code here:
        util.ShowPanel(new School(), content, 738, 528);
        txt_title.setText("Credencial Escolar");
    }//GEN-LAST:event_btn_schoolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        FlatMaterialLighterIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    public void handleChangeTitle(String title){       
        header.removeAll();
        txt_title.setText("hola");
        header.setBackground(Color.red);
        header.revalidate();
        header.repaint();
        
//        System.out.println("com.proyecto.main.Dashboard.handleChangeTitle()");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aside;
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_cards;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_identification;
    private javax.swing.JButton btn_membership;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_school;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt_logo;
    public static javax.swing.JLabel txt_title;
    // End of variables declaration//GEN-END:variables
}
